### ISSUE TITLE
State of v7 navigator is kept in memory when navigating to v10

### ISSUE THREAD

**Issue by gilberto-torrezan** [vaadin/multiplatform-runtime#10]
@stefanuebe commented on [Wed Sep 05 2018](https://github.com/vaadin/multiplatform-runtime-internal/issues/212)

Following steps to reproduce the problem:
1. navigate to a v7 view (e.g. "#!bar")
2. navigate to a v10 view (e.g. "/foo").
3. navigate to the same v7 view ("#bar").

The v7 navigator now thinks that the v7 is still shown and not navigate to it. Instead the method `updateNavigationState` is called, which has no effect for the ui, since no listeners are fired or notified. Therefore a content update based on the view is not possible.

Happening in Navigator @ line 580+.

If that cannot be handled automatically, a workaround or "how to" should be put into the documentation.

---

@caalador commented on [Fri Sep 07 2018](https://github.com/vaadin/multiplatform-runtime-internal/issues/212#issuecomment-419311695)

Just askin for a clarification. 
The navigation is done through the Navigator or the browser as:
- http://localhost:8080/#!bar
- http://localhost:8080/foo
- http://localhost:8080/#!bar

**Comment by stefanuebe** [comment]
Yes, but only via programmatical navigation, not via browser.

**Comment by caalador** [comment]
Can you give a sample of the usage as I always get `navigateTo` called when coming to a FW7 view from a Flow view in the `mpr-tests/navigation` module.
