### ISSUE TITLE
ViewAccessChecker limitation with ConnectorResourceHandler

### ISSUE THREAD

**Issue by javier-godoy** [vaadin/multiplatform-runtime#110]
The current flow `VaadinServletRequest` is null when navigation is initiated from a legacy `ConnectorResourceHandler`, causing [ViewAccessChecker ](https://github.com/vaadin/flow/blob/5fa90d6eeb497292eeed512ba369828f6112cff7/flow-server/src/main/java/com/vaadin/flow/server/auth/ViewAccessChecker.java#L144)to prevent navigation "because no HTTP request is available for checking access".

```
var current = com.vaadin.flow.component.UI.getCurrent();

FileDownloader buttonWrapper = new FileDownloader(new StreamResource(() -> {
	current.navigate(FlowView.class);
	return new ByteArrayInputStream(new byte[0]);
}, "file.txt"));

Button myButton = new Button("Click to download");
buttonWrapper.extend(myButton);
```		
[Full example](https://github.com/vaadin/multiplatform-runtime/files/8224325/mpr-test-v23.zip)
- Execute the application `mvn jetty:run`
- Open http://127.0.0.1:8080/
- Click "Home"
- Click "Click to Download" (remember to disable cache)
- A file is downloaded and the browser navigates to http://127.0.0.1:8080/flow
- Observe that `VaadinServletRequest.getCurrent()` is logged as `null` in `FlowView::beforeEnter` .

Versions: Vaadin 23.0.1 / 8.14.3

**Comment by caalador** [comment]
Navigating away during a download stream initialization doesn't sound right. 
If you want to navigate away on the button click while starting a download you should just use the click event for navigation instead of mixing with the FileDownloader extension stream generation 

e.g. changing the code to:
```
		FileDownloader buttonWrapper = new FileDownloader(new StreamResource(() -> {
			return new ByteArrayInputStream(new byte[0]);
		}, "file.txt"));

		Button myButton = new Button("Click to download", click ->
				current.access(() -> current.navigate(FlowView.class)));
```

**Comment by ghost** [comment]
> يكون التدفق الحالي `VaadinServletRequest`فارغًا عند بدء التنقل من نظام قديم `ConnectorResourceHandler`، مما يتسبب في [قيام ViewAccessChecker](https://github.com/vaadin/flow/blob/5fa90d6eeb497292eeed512ba369828f6112cff7/flow-server/src/main/java/com/vaadin/flow/server/auth/ViewAccessChecker.java#L144) بمنع التنقل "نظرًا لعدم توفر طلب HTTP للتحقق من الوصول".
> 
> ```
> var current = com.vaadin.flow.component.UI.getCurrent();
> 
> FileDownloader buttonWrapper = new FileDownloader(new StreamResource(() -> {
> 	current.navigate(FlowView.class);
> 	return new ByteArrayInputStream(new byte[0]);
> }, "file.txt"));
> 
> Button myButton = new Button("Click to download");
> buttonWrapper.extend(myButton);
> ```
> 
> [المثال الكامل](https://github.com/vaadin/multiplatform-runtime/files/8224325/mpr-test-v23.zip)
> 
> * قم بتنفيذ التطبيق`mvn jetty:run`
> * افتح http://127.0.0.1:8080/
> * انقر فوق "الصفحة الرئيسية"
> * انقر فوق "انقر للتنزيل" (تذكر تعطيل ذاكرة التخزين المؤقت)
> * يتم تنزيل ملف وينتقل المتصفح إلى http://127.0.0.1:8080/flow
> * لاحظ أنه `VaadinServletRequest.getCurrent()`تم تسجيل `null`الدخول `FlowView::beforeEnter`.
> 
> الإصدارات: Vaadin 23.0.1 / 8.14.3

Ok

**Comment by mshabarov** [comment]
Closed due to no response from author. If this is still an issue, please reopen the ticket and provide more information.
