### ISSUE TITLE
CurrentInstance not cleared when request made to /framework

### ISSUE THREAD

**Issue by pogocode** [vaadin/multiplatform-runtime#118]
When a request is made to framework, the `VaadinSession`s are not cleared. Consequently calls to `VaadinSession.getCurrent()` may return data related to unrelated sessions at the start of the next http request.

When using Spring Boot / Spring Security, this is a problem if using servlet filters which rely on `com.vaadin.flow.spring.security.VaadinAwareSecurityContextHolderStrategy`, as we can end up with the incorrect `SecurityContext` being returned, although this is outside the scope of the minimal example that I have provided.

### Minimal reproducible example

I have attached a slightly modified version of an MPR sample that I was provided by Vaadin support. 

The `org.vaadin.mprdemo.VaadinSessionWebFilter` logs when the `VaadinSession`s are unexpectedly set before / after requests. 

`mpr-demo-mpr-6-current-instance.zip`

Reproduction steps:

1. Run `mvn jetty:run`
2. Navigate to http://localhost:8080/legacy
3. View logs - repeated requests to the http://localhost:8080/legacy will demonstrate the issue

### Expected behaviour

`com.vaadin.flow.server.VaadinSession.getCurrent()` and `com.vaadin.server.VaadinSession.getCurrent()` should return null at the end of the request, and should return null at the start of any subsequent requests.

### Actual behaviour

`VaadinSession`s are not cleared. Consequently calls to `VaadinSession.getCurrent()` may return data related to unrelated sessions at the start of the next HttpRequest.

An attempt to clear CurrentInstance is made in `com.vaadin.server.VaadinService#requestEnd` when processing the `/framework` request, but further requests to `CurrentInstance.get(VaadinSession.class)` will then use the fallback resolver that were registered in `com.vaadin.mpr.core.AbstractMprServlet#servletInitialized`.

The following logging from the `org.vaadin.mprdemo.VaadinSessionWebFilter` in the attached sample MPR project demonstrates this:

VaadinSessions still set at the end of request to `/framework`:

```
17:24:36.772 [qtp218045011-50] ERROR org.vaadin.mprdemo.VaadinSessionWebFilter - Vaadin Session still set after servlet processing finished - request URI: [Request(POST //localhost:8080/framework?v-1669224276408)@3e346ce9] flow session: [com.vaadin.flow.server.VaadinSession@349fb5b9], v8 session: [com.vaadin.mpr.core.MprSession@6556f83f]
```

VaadinSessions already set at start of next request: 

```
17:24:40.965 [qtp218045011-50] ERROR org.vaadin.mprdemo.VaadinSessionWebFilter - Vaadin Session already set - request URI: [Request(POST //localhost:8080/?v-r=uidl&v-uiId=0)@72f384c6] flow session: [com.vaadin.flow.server.VaadinSession@349fb5b9], v8 session: [com.vaadin.mpr.core.MprSession@6556f83f]
```

### Versions:
    - Vaadin Framework: 8.16.1
    - Flow: 23.2.5
    - MPR: 6.0.3
    - Java JRE / JDK: 17

```
openjdk 17.0.2 2022-01-18 LTS
OpenJDK Runtime Environment Corretto-17.0.2.8.1 (build 17.0.2+8-LTS)
OpenJDK 64-Bit Server VM Corretto-17.0.2.8.1 (build 17.0.2+8-LTS, mixed mode, sharing)
```
    - Operating System: OSX 12.6 (21G115)
    - Browser (if applicable): Chrome Version 107.0.5304.110 (Official Build) (x86_64)

[mpr-demo-mpr-6-current-instance.zip](https://github.com/vaadin/multiplatform-runtime/files/10078135/mpr-demo-mpr-6-current-instance.zip)

**Comment by TatuLund** [comment]
I needed to change from logger to system.out in order to get the output. But yes, I see the same behavior after this modification using Vaadin 23.2.8, Vaadin 8.18.

```
@WebFilter(value="/*", asyncSupported=true)
public class VaadinSessionWebFilter implements Filter {

    @Override
    public void doFilter(ServletRequest request, ServletResponse response,
                         FilterChain chain) throws IOException, ServletException {

        alertIfSessionSet(request, "Vaadin Session already set");

        try {
            chain.doFilter(request, response);
        } finally {
            alertIfSessionSet(request, "Vaadin Session still set after servlet processing finished");
        }
    }

    private void alertIfSessionSet(ServletRequest request, String prefix) {
        VaadinSession vaadinSession = VaadinSession.getCurrent();
        com.vaadin.server.VaadinSession v8Session = null;
        if (vaadinSession != null) {
            vaadinSession.lock();
            try {
                v8Session = com.vaadin.server.VaadinSession.getCurrent();
            } finally {
                vaadinSession.unlock();
            }
        }
        if (vaadinSession != null) {
            System.out.println(prefix+" - request URI: ["+request+"] flow session: ["+vaadinSession+"], v8 session: ["+v8Session+"]");
        }
    }

    @Override
    public void init(FilterConfig filterConfig) {
    }

    @Override
    public void destroy() {
    }
}

```

**Comment by pogocode** [comment]
Just a note to say that we can add a filter at the start of the chain to call `CurrentInstance.clearAll()` as a workaround.

**Comment by mshabarov** [comment]
The pull request containing a possible solution is on the code review.

**Comment by mshabarov** [comment]
The PR fixing the issue was merged and changes will be delivered in the following versions: 2.2.13, 6.0.4, 6.1.1, 7.0.0.alpha2.
