### ISSUE TITLE
MPR Push Configuration NPE 

### ISSUE THREAD

**Issue by angelsinistanbul** [vaadin/multiplatform-runtime#121]
Hello,

I am migrating the vaadin v7 application with using MPR to vaadin 14. We are using Push mode manual. I migrate to Push mode by using flow imports. However, I am facing nullpointerexception. How can handle this I do not know. Becase, no documents o net. Hope you all help me.

`java.lang.NullPointerException at com.vaadin.mpr.core.MprPushConfiguration.getPushMode(MprPushConfiguration.java:31) at com.vaadin.server.VaadinSession.unlock(VaadinSession.java:1000) at com.vaadin.server.VaadinService.requestEnd(VaadinService.java:1382) at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1449) at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:380) at javax.servlet.http.HttpServlet.service(HttpServlet.java:779) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:239) at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:215)`

**Comment by TatuLund** [comment]
This looks the same as https://stackoverflow.com/questions/75659498/vaadin-7-to-14-com-vaadin-mpr-core-mprpushconfiguration-getpushmode

> com.vaadin.server.VaadinSession.unlock(VaadinSession.java:1000) at

This codeline reference points to Vaadin 7 version that is potentially too old to work with the latest version of Multiplatform Runtime product. Although I would expect to see an other error.

However this NPE is possible only when getPushMode is called before MPR has completely initialized, which indicates that there is some problem elsewhere that has prevented that to happen. You have probably still some legacy Servlet use left.
