### ISSUE TITLE
Legacy URL fragment lost after navigation

### ISSUE THREAD

**Issue by javier-godoy** [vaadin/multiplatform-runtime#123]
MPR (Vaadin 23.3.6/7.7.38) with MprNavigatorRoute. Chrome 111.

There are two legacy views. After navigation from `http://127.0.0.1:8080/#!view1` to `http://127.0.0.1:8080/#!view2`, the target URL is visible for a split second, then the URL reverts to `http://127.0.0.1:8080/`

![mpr](https://user-images.githubusercontent.com/11554739/232847981-d223ab93-8b15-4007-857a-a861f820c8f5.gif)

```
@Route("")
public class MyNavigatorRoute extends MprNavigatorRoute {
    @Override
    public void configureNavigator(Navigator navigator) {
      navigator.addView("view1", View1.class);
      navigator.addView("view2", View2.class);
    }
}


public class View1 extends VerticalLayout implements View {

  @Override
  public void enter(ViewChangeEvent event) {}
  
  public View1() {
    setCaption("View 1");
    addComponent(new Button("Navigate", ev -> {
      getUI().getNavigator().navigateTo("view2");
    }));
  }
  
}

public class View2 extends VerticalLayout implements View {

  @Override
  public void enter(ViewChangeEvent event) {}
  
  public View2() {
    setCaption("View 2");
  }
  
}
```

**Comment by tltv** [comment]
Tried this out and this is not an issue with Vaadin 8. Vaadin 7 clears the state after a small delay. Bug in Vaadin 7 navigator maybe. I wonder if its known issue even without MPR.

Workaround is to run a Javascript snippet in `enter(ViewChangeEvent)` to update state with `window.history.pushState`.
```
@Override
public void enter(ViewChangeEvent event) {
	if(!Objects.equals(event.getOldView(), this)) {
		event.getNavigator().getUI().getPage().getJavaScript().execute(
				"setTimeout(() -> window.history.pushState('" + event.getViewName() + "', '', ''))");
	}
}
```
