### ISSUE TITLE
Allow to configure MprServlet to support reverse proxy mapping

### ISSUE THREAD

**Issue by Tristan-EC** [vaadin/multiplatform-runtime#125]
Using vaadin flow 14.9.7, vaadin 8.20.0 and mpr-v8 2.2.13

Hi. I'm migrating a vaadin7/8 application using MPR.
We use a RPM (reverse proxy mapping) to map our application url.
We have something like this:
https://domain/env/application -> http://server:port/application (context root is 'application').

The application cannot find its "vaadinBootstrap.js". 
It tries to get the resource from https://domain/application/framework/VAADIN/vaadinBootstrap.js (missing env) instead of https://domain/env/application/framework/VAADIN/vaadinBootstrap.js (where it's available)

The problem is coming from the extra "env" in the address (without the env part, it works)

I have tried already to define a DependencyFilter to adapt the url of "vaadinBootstrap.js".
It works to load the initial file but later it calls vaadin.initApplication() (javascript calls) with "wrong" appConfig (according the RPM)

![Screenshot from 2023-05-04 10-55-19](https://user-images.githubusercontent.com/132680629/236481136-c27ef96f-f806-4bc4-989e-c89247cd5de1.png)

Could you allow to configure MPR servlet with customized parameters?
I should be able to define the "virtual" context root to use. In my case: env/application

Right now, I cannot deploy the application on some environments due to this limitation.

Thank you.

**Comment by Legioth** [comment]
I wonder if we should classify this as a bug? Vaadin in general is supposed to support path rewrites done by reverse proxies by always using relative URLs. If MPR is not using a relative URL for this case, then that sounds like a defect rather than a missing feature.

**Comment by Tristan-EC** [comment]
> I wonder if we should classify this as a bug? Vaadin in general is supposed to support path rewrites done by reverse proxies by always using relative URLs. If MPR is not using a relative URL for this case, then that sounds like a defect rather than a missing feature.

@Legioth I'm agree that it's more a bug than an enhancement.
It works with vaadin7/vaadin8 application.
