### ISSUE TITLE
Loading indicator loads indefinitely when a dialog is open despite app being functional

### ISSUE THREAD

**Issue by jameskerr06** [vaadin/multiplatform-runtime#126]
We have a Vaadin app running 23.3.12, 8.20.0 and MPR 6.1.2.

We have a v23 view which allows you to open a dialog. We've noticed that the loading indicator sometimes starts and then never stops blinking. Its possible to close the dialog and interact with the app but the loading indicator remains blinking.

One way to trigger the issue is to resize the browser when the dialog is open.

I have attached a standalone application which reproduces the issue. 

I spoke to Vaadin support on the live chat and they were able to reproduce on my simple app (which is MPR). They were not able to reproduce on V23 without MPR so I think this is an MPR issue.
 
[mpr-demo-loadingbar.zip](https://github.com/vaadin/multiplatform-runtime/files/11734912/mpr-demo-loadingbar.zip)

Steps to reproduce:
- Download the attached app and extract
- Run "mvn -Pproduction"
- Open the browser and navigate to http://localhost:8080/legacy
- Click the button to open the dialog
- resize the browser window
- Notice the loading indicator appears (blue blinking bar at the top of the window)

I would expect the loading indicator to stop blinking and disappear.

In the sample app, if you comment out line 68 of MyUI (`childWrapper.getElement().appendChild(content.getElement());`) There will be no v8 components on the screen. If you do this, the issue is not reproducible. So I think it must be an MPR issue.

**Comment by mcollovati** [comment]
The issue was triaged and currently added to the backlog priority queue for further investigation

**Comment by mcollovati** [comment]
The issue was assigned to a developer and is currently being investigated

**Comment by mcollovati** [comment]
The PR fixing the issue was merged and changes will be delivered in the following versions: 7.0.6, 6.1.8
