### ISSUE TITLE
A component with setResponsive(true) does not get updated width ranges when running inside of a LegacyWrapper. 

### ISSUE THREAD

**Issue by petrixh** [vaadin/multiplatform-runtime#23]
Attached example project has a native v7 and a mpr-v7/v10 project (ignore the native v10 project). 

Example has 2 labels and a CssLayout, the first label follows the width ranges of the UI, while the second follows the width ranges of the CssLayout (also not working if a panel is used so not just CssLaoyut specific)

When running the v7 project, setResponsive on a CssLayout updates the width ranges without incident, however when running the v7mpr project the width range is updated once when the application loads, however resizes do not trigger updates after that. 

If you open up the browser console and type vaadin.forceLayout() the width ranges are updated. The demo has 2 rules < 500px (blue), 501px-800px (yellow) 

Env: 
Java: Java 8 (won't compile on Java 10, will nag about widgetset descriptor inheritance)
Vaadin: 7.7.14
MPR: 1.0.0.beta1
Browser: Chrome 69
OS: OS X 10.13.6

[mprresponsivebug.zip](https://github.com/vaadin/multiplatform-runtime/files/2426068/mprresponsivebug.zip)

**Comment by TatuLund** [comment]
See also

https://vaadin.com/forum/thread/17758035/mpr-vaadin-7-and-grid-resize-issue-chrome
