### ISSUE TITLE
Invalidating the session causes unhandled exception due to flow session not found

### ISSUE THREAD

**Issue by petrixh** [vaadin/multiplatform-runtime#24]
Invalidating a HTTP session when MPR is running causes an unhandled exception when MPR is looking for a Flow session. 

Example included, in v7/v8 the recommended way of "logging out a user" was to invalidate the current HTTP session and call page.refresh() which usually landed on the login page of an app. However, in MPR this seems to be quite hard to achieve. 

It would be good to document how in mpr/v10 one should kill the session and refresh the browser in a way that allows us to land on a Vaadin page in a controlled manner. 

Example app included with v7/v7mpr examples: 

Env:
Java: Java 8 (won't compile on Java 10, will nag about widgetset descriptor inheritance)
Vaadin: 7.7.14
MPR: 1.0.0.beta1
Browser: Chrome 69
OS: OS X 10.13.6

[mprsessioninvalidationbug.zip](https://github.com/vaadin/multiplatform-runtime/files/2426114/mprsessioninvalidationbug.zip)

**Comment by gilberto-torrezan** [comment]
Hi @petrixh, this bug is fixed on the latest release (`1.0.0`). I've created a PR to update the documentation, adding a topic on how to deal with `VaadinSession` when using MPR.

Basically you need to use Flow APIs to invalidate it:

```java
Button close = new Button("Close session", event -> {
    UI.getCurrent().getPage()
        .executeJavaScript("window.location.reload();");
    VaadinSession.getCurrent().getSession().invalidate();
});
```
