### ISSUE TITLE
Interacting with V7 Page (or Navigator) during V7 init causes NPE

### ISSUE THREAD

**Issue by petrixh** [vaadin/multiplatform-runtime#26]
If the UI code interacts with the V7 page object during initialization a NPE is thrown because the legacy Page object does not have its location set. This is quite typical behavior in old V7/v8 apps where the URI fragment is kept in the browser while the user logs on, and after logon the code calls getUi().getNavigator().navigateTo(getUI().getNavigator().getSate()). In other cases we might check !getNavigator().getState().trim().isEmpty() and navigate to a default view other than "". 

Traced it down to something to do with initialization order, if I don't ask the page/navigator for its state from the UI code during initialization all goes well and the navigator will navigate to the appropriate view. 

Including example app that tries to demonstrate the behavior (ignore the v7 and v10 playgrounds)
Run the v7mpr playground and open a browser to localhost:8080, between tests you'll need to invalidate the session in order to reset everything (there's a button for this)

Scenario 1: 
- Click on the "init v7 content without interaction with v7" and notice that the application navigates to view1 without incident

Scenario 2: 
- Click on the second button "init v7 and navigate..." which will try to check the navigator state in order to navigate (will blow up in an NPE inside of Page.java)

Scenario 3: (remember to invalidate the session between tests)
- click on the "Create dummy LegacyWrapper" button
- click on "init v7 and navigate" and notice that this time the initial check passed fine

Scenario 4: (remember to invalidate)
- Change the url to http://localhost:8080/#!view2 
- after this, click on the first button (without interaction) and notice that the navigator was able to navigate to view 2 without incident, view2 will check the fragment from the page,

It almost feels like the LegacyUI#init method happens very very late in the process or if no LegacyWrapper is attached, it will not happen at all. In scenario 3, we simply added a invisible LegacyWrapper to the DOM in order to get the UI and Page objects from V7 initialized so that our UI code can check the Navigator state (and by definition the page location and fragment). 

Attached demo project: 
Java 8 (required)
Vaadin 7.7.14
MPR: 1.0.0
Chrome (latest)
OS X (latest high sierra)

[mprpageinitbug.zip](https://github.com/vaadin/multiplatform-runtime/files/2436119/mprpageinitbug.zip)

**Comment by mehdi-vaadin** [comment]
Using navigator in MPR works as explained in the documentation. As @pleku mentioned, the case mentioned in this issue is not supported. And, to make it clear, the documentation's been updated and improved.
