### ISSUE TITLE
MPR + Vaadin 7 screen resolution sensitivity

### ISSUE THREAD

**Issue by mobileWMS** [vaadin/multiplatform-runtime#58]
MPR + Vaadin 7 is much more sensitive to resolution changes then the corresponding pure Vaadin 7 app.  Certain places add full browser scrollbars in MPR + Vaadin 7 that do not for pure vaadin 7.

Resolution: [1920 x 1080, 150%](https://i.postimg.cc/XvmpW3Tg/Resolution-For-Vaadin-Test.png)
Pure Vaadin 7 app looks perfect: [here](https://i.postimg.cc/Rh08T5Zj/Veeder-Pure-Vaadin7-Plan-Form.png)
MPR + Vaadin 7 app, note browser wide scrollbars: [here](https://i.postimg.cc/GtNMJ4Ny/Veeder-MPRVaadin7-Plan-Form.png)

Some basic things about my app.  First, the structure:
- Flow Div ( entry point, where Route is "" )
  - Flow VerticalLaout
     - Vaadin 7 components wrapped in LegacyComponent 

The MPR + Vaadin 7 app is virtually the same as the pure Vaadin 7 app.  I actually just merge the changes from Vaadin 7 app to MPR app to keep them in sync.  So there are differences, just not many once you get into the application.  Now, a snipped portion of entry point class:
```
//@Viewport("width=device-width")
//@Viewport( Viewport.DEVICE_DIMENSIONS)
//@Viewport( Viewport.DEFAULT)
@Viewport("width=device-width, minimum-scale=1.0, initial-scale=1.0, user-scalable=yes")
//@Viewport( Viewport.DEVICE_HEIGHT)
@MprWidgetset("com.mobiwms.website.WmsWidgetSet")
@PageTitle("Turnsmith 2.0")
@JsModule("./js/addBeforeUnloadListener.js")
@JsModule("./js/logToConsole.js")
@Push
//@Push(value = PushMode.MANUAL, transport = Transport.WEBSOCKET)
@SuppressWarnings("serial")
@MprTheme("mobiwms")
//@PreserveOnRefresh
@Route("")
@RouteAlias("entry")
public final class WmsEntryPoint extends Div
	implements HasLegacyComponents,PageConfigurator,RouterLayout,
	BeforeEnterObserver,AfterNavigationObserver  {
  /*code to build the UI, as documented in MPR documentation, replacement for UI
   * So I create the VerticalLayout here, add it to Div, and, based on my needs ( has the user logged
   *  in, and so on ), wrap either the Vaadin 7 based login panel or Vaadin 7 application panel in
   *  LegacyComponent, adding LegacyComponent to VerticalLayout.
   *  There is always only one component in this VerticalLayout, either the Login pane or the
   *  application pane.
   */
  ...
}
```

We can sort of work around it by changing a TabSheet from being 100% width to 99.9% width, [here](https://i.postimg.cc/rsvJRv0G/MPRPlan-Form.png), but this sort of suggests a problem with MPR to me.  Also, on another monitor it might not work (I was told by a user it did not work on his, with the same exact monitor resolution settings ).  In this mostly working version (99.9%), I, as per advice from Vaadin, kept changing width and playing with width until I found the component that was causing the overlap, and then found the largest percentage that would not cause browser wide scrollbars.  My concern is that the MPR is so sensitive to such differences for the contained/wrapped Vaadin 7 app.  Maybe MPR should protect Vaadin 7 and 8 apps better from this kind of stuff, or maybe documentation can be added that can help developers protect against it.

**Comment by mehdi-vaadin** [comment]
@mobileWMS thanks for reporting this issue. Can you please help us and share a minimal reproducible example of it? Reproducing this issue and then fixing it with the current information would be really difficult.

**Comment by TatuLund** [comment]
This could be related https://github.com/TatuLund/devday-demo-flow/blob/master/src/main/java/com/vaadin/devday/demo/views/GridView.java

See the proposed workaround in the linked discussion thread.

**Comment by mobileWMS** [comment]
What discussion thread?

**Comment by TatuLund** [comment]
@mobileWMS , sorry I had copied wrong link, corrected now.

**Comment by mobileWMS** [comment]
Yep, already do that, BUT maybe I should experiment more inside that browser resize listener.  In my case, the user with the different resolution is not actually changing things, resizing the browser ( at least not after he does his initial setting of resolution ).  I have to in order to repeat his issue, of course, but in his case, with no change to browser size or resolution, one browser tab with pure Vaadin 7 app, another with same Vaadin 7 app wrapped in MPR, and the MPR one is where the problem occurs.  Regardless, worth some experiments with `forceLayout`, so thanks.

One addition: I have not confirmed this, but he connects it to the browser zoom feature.  Not that he is constantly zooming in and out, because he does not.  Just that he zoomed in one time with his browser, and left it that way.  So it might be a combination of screen resolution and browser zoom.

**Comment by mobileWMS** [comment]
See attached.  I simply went to a tutorial provided by you guys [here](https://vaadin.com/learn/training/v10-migration-mpr) and did the following:

1. Downloaded the excercises
2. Moved dashboard and solution-dashboard to my eclipse folder
3. Changed my resolution to match what I said above
4. Ran each with "mvn jetty:run"
5. For "dashboard", I got a [perfect experience](https://i.postimg.cc/rp4BfFzd/dashboard-Pure-Vaadin7.png).  For "solution-dashboard", I got the [scroll bar problem I mentioned above](https://i.postimg.cc/zXf49kVY/solution-dashboard-MPR.png).

I made no change to the code.  See attached for the broken one ( I cannot attach the vaadin 7 one because it is too big ).  If you want the vaadin 7 version, I will see what I can do.  But I litterally doownloaded it today, and did the tests today, so you can probably just use the dashboard projects from the tutorial as en example.

[solution-dashboard.zip](https://github.com/vaadin/multiplatform-runtime/files/4228210/solution-dashboard.zip)

**Comment by mobileWMS** [comment]
I made trimmed down versions based on that tutorial, and here is the information.

Display settings: [here](https://i.postimg.cc/JzN8byYP/Display-Settings150-Resolution-Test.png)

Pure vaadin 7:
1. [trimmed-dashboard.zip](https://github.com/vaadin/multiplatform-runtime/files/4233332/trimmed-dashboard.zip)
2. [Transactions (note that there is no bar at bottom)](https://i.postimg.cc/Y9hqfrW0/dashboard-Transactions-150-Resolution-Test.png)


MPR Version:  
1. [trimmed-solution-dashboard.zip](https://github.com/vaadin/multiplatform-runtime/files/4233354/trimmed-solution-dashboard.zip)
2. [Transactions (note bar at bottom)](https://i.postimg.cc/xCJnN6wb/solutiondashboard-Transactions-150-Resolution-Test.png)

**Comment by TatuLund** [comment]
In case you have issue not in browser resize, you can do the JavaScript call of vaadin.forceLayout() also after Vaadin 7 component has been attached.

**Comment by mobileWMS** [comment]
Would this also work for the FileDownloader problem ( #57 )?

**Comment by mobileWMS** [comment]
I added it to the end of the `DashboardEntryPoint()` contructor, after everything was added, and it did not fix things ( see trimmed solution-dashboard for the original code, before my change below ):
```
    public DashboardEntryPoint(){
        setSizeFull();
        content.setSizeFull();
        UI.getCurrent().setLocale(Locale.US);
        add(new LegacyWrapper(content));

        DashboardEventBus.register(this);
        Responsive.makeResponsive(content);
        content.addStyleName(ValoTheme.UI_WITH_MENU);

        updateContent(false);

        // Some views need to be aware of browser resize events so a
        // BrowserResizeEvent gets fired to the event bus on every occasion.
        Page.getCurrent().addBrowserWindowResizeListener(
                new BrowserWindowResizeListener() {
                    @Override
                    public void browserWindowResized(
                            final BrowserWindowResizeEvent event) {
                        DashboardEventBus.post(new BrowserResizeEvent());
                    }
                });
        getUI().ifPresent(ui -> {
        	ui.getPage().executeJs("vaadin.forceLayout()");
        });
    }
```

That said, maybe it needs to be added someplace else?  I mean, this is the only place I explicitly add Vaadin 7, but maybe this is not the correct place to add this line of code?

**Comment by TatuLund** [comment]
You should not add browser resize listener in constructor, but onAttach and remember to unregister it onDetach, I copied the workaround example from Forum here:

```
private Registration listener;

@Override
protected void onAttach(AttachEvent attachEvent) {
	super.onAttach(attachEvent);
        // uncomment the line below if you need workaround also when not resizing
        // ui.getPage().executeJavaScript("vaadin.forceLayout()");
	getUI().ifPresent(ui -> listener = ui.getPage().addBrowserWindowResizeListener(event -> {
		ui.getPage().executeJavaScript("vaadin.forceLayout()");
	}));
}

@Override
protected void onDetach(DetachEvent detachEvent) {
	// It is needed to remove the BrowserWindowResizeListener during detach
	// in order not to bloat browser resources
	listener.remove();
	super.onDetach(detachEvent);
}
```

**Comment by mobileWMS** [comment]
Good catch.  I copied it from one of the tutorials, and did not even remember that little nuance.  Regardless, it did not  fix my issue.  My issue is not a "resize" issue, it is a "resolution" issue.  In other words, unlike me, the user keeps the same resolution all the time, they hardly ever change it ( or zoom in or out via the browser, since the "zoom" level is where they want it ).  I am changing the resolution to test theories, but I always test with a totally fresh browser, so even in my case it is not a "resize" issue.  It should be easy to repeat with either the zip above, or with a dummy project I created [here](https://github.com/mobileWMS/solution-dashboard).  This dummy project has the latest Vaadin as of the writing of this comment ( 14.1.17 ), and it has your suggested changes.  Hope this helps find either a workaround or the root cause.

**Comment by mobileWMS** [comment]
What is the status of this?  I linked an example project, so in theory you should have a decent test case.  I don't currently use MPR, but we might need to in the next year as we restart the upgrade to Vaadin 14, so wanted to followup on this.

**Comment by TatuLund** [comment]
This issue is fixed by https://github.com/vaadin/multiplatform-runtime-internal/pull/423
