### ISSUE TITLE
"hidden" scroll bar that you need to reveal by panning in order to scroll the view.

### ISSUE THREAD

**Issue by mstahv** [vaadin/multiplatform-runtime#59]
Feedback from a customer: with their app there is "hidden" scroll bar that you need to reveal by panning in order to scroll the view. This does not happen with Vaadin 7 native, only with MPR.

Screenshots and more details in prodpad: https://app.prodpad.com/feedback/418522/canvas

**Comment by mehdi-vaadin** [comment]
It might be a duplicate of #58.

**Comment by mehdi-vaadin** [comment]
I'm closing this in favor of #58
