### ISSUE TITLE
StringIndexOutOfBoundsException when MainView is AbstractMprRouteAdapter and navigation is performed to non-existing view

### ISSUE THREAD

**Issue by mvysny** [vaadin/multiplatform-runtime#62]
Vaadin 14.1.16, MPR 2.0.1

If you have a MainView extending AbstractMprRouteAdapter mapped to an empty route (""), then any navigation to a non-existing view fails within the AbstractMprRouteAdapter with:

```
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1967)
	at com.vaadin.mpr.core.AbstractMprRouteAdapter.setParameter(AbstractMprRouteAdapter.java:153)
	at com.vaadin.mpr.core.AbstractMprRouteAdapter.setParameter(AbstractMprRouteAdapter.java:45)
	at com.vaadin.flow.router.internal.NavigationStateRenderer.notifyNavigationTarget(NavigationStateRenderer.java:90)
	at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.handle(AbstractNavigationStateRenderer.java:212)
	at com.vaadin.flow.router.Router.handleNavigation(Router.java:223)
```

**Comment by caalador** [comment]
What would be the expected outcome for the non existent navigation?
The RouteAdapter is a wildcard adapter so we can show the page without the params or we could redirect to route not found error page. Not certain what the expectation should be...

**Comment by mvysny** [comment]
Hard to say. Technically AbstractMprRouteAdapter accepts a wildcard - any path or anything after the view name. That technically makes AbstractMprRouteAdapter a catch-all page. We either leave this as-is (and introduce AbstractMprRouteParameterlessAdapter, and just fix the StringIndexOutOfBoundsException), or we introduce a special case for `"/"`-mapped AbstractMprRouteAdapter which would accept no parameters...

Since Views overwhelmingly do not have any parameters, I'd expect AbstractMprRouteAdapter to take no parameters (a breaking change), we can introduce AbstractMprWildcardRouteAdapter and we can leave this up to the person doing the migration to decide. I'd personally vote for this option, even though it's a breaking change.

**Comment by mvysny** [comment]
However, there is a bug #61 where we can discuss this (potentially breaking) change.

Therefore, in this bug I'd propose to simply leave everything as-is and just fix the StringIndexOutOfBoundsException.
