### ISSUE TITLE
NPE in AbstractLegacyEmbed.setRequest()

### ISSUE THREAD

**Issue by mvysny** [vaadin/multiplatform-runtime#75]
Greetings, Vaadin 8.8.5, MPR 2.0.3 (probably - need to verify). I have the following stacktrace:
```java
Caused by: java.lang.NullPointerException: null
        at com.vaadin.server.communication.ServerRpcHandler$RpcRequest.<init>(ServerRpcHandler.java:100)
        at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:232)
        at com.vaadin.mpr.core.AbstractLegacyEmbed.setRequest(AbstractLegacyEmbed.java:144)
        ... 89 common frames omitted
```
The NPE most probably happens because `legacyRequest` is null at `AbstractLegacyEmbed:142`. We need to understand why the `VaadinService.getCurrentRequest()` could possibly return null, in order to understand what's going on and possibly design a workaround. At which point the V8 current request is set in the MPR please?

After the NPE occurs, the client-side stops reacting to client clicks (stops sending server requests), showing a blue progress bar. The application becomes absolutely unusable; this is a blocker.

**Comment by caalador** [comment]
Which Flow & Paltform version?
The client-side stops due to the fact that it's waiting for a response from the server which it doesn't get as the response is not scheduled due to the npe.

**Comment by caalador** [comment]
On route to check would be to check that are the fallback resolvers set to the CurrentInstance or are they for some reason left out e.g. AbstractMprServlet::init is not executed or the if is skipped without the resolvers having been set even once.
As the flow request is there due to the rpc request, and with the fallback resolver we should always get a FW request as a MprRequest that is created in the fallback.

**Comment by mvysny** [comment]
Sorry for missing info, it's Vaadin 14.2.3, flow 2.2.3, MPR 2.0.3.

> On route to check would be to check that are the fallback resolvers set to the CurrentInstance or are they for some reason left out e.g. AbstractMprServlet::init is not executed or the if is skipped without the resolvers having been set even once.

This is precisely the kinds of checks which I had in mind for the MPR to perform. It's much easier for the MPR to examine the environment in production than for a programmer; the programmer may not even know which bits to check.

Could it be that Spring might not be calling AbstractMprServlet::init in a special environment for some reason, e.g. that the classpath scanning could somehow omit that class?

**Comment by caalador** [comment]
So the Spring spoon is also in the soup?

**Comment by mvysny** [comment]
Yes, unfortunately.

**Comment by mvysny** [comment]
The `VaadinServlet.init(ServletConfig)` calls `super.init(ServletConfig)`  which calls `GenericServlet.init()` which calls `AbstractMprServlet.init()` which lets an not-yet-initialized servlet escape to a static context

I'm hardening the MPR and reworking the initialization to be safer.
