### ISSUE TITLE
Dialog size information isn't communicated properly to MPR

### ISSUE THREAD

**Issue by Ansku** [vaadin/multiplatform-runtime#76]
In 14.2 branch V8 contents within a Dialog have their layouting triggered before Dialog gains its actual size, and the layouting isn't retriggered once that has happened. Likewise it's not triggered if the Dialog's size is changed either manually or programmatically. For elements that have programmatically calculated fixed sizes, such as TabSheet contents, this leads to too small final sizes.

Test project that reproduces the issue can be found attached in https://vaadin.com/pro/support#3435 (accessible by Vaadin staff only)
Tested on 14.2.1 and 14.2.3.

Workarounds:
1. Give Dialog contents fixed size so that the elements deeper within the layout don't have to measure themselves based on Dialog's size.
2. `dialog.getElement().executeJs("vaadin.forceLayout()");` whenever initializing or resizing happens -- only works out-of-the-box if MPR has already been initialized when the Dialog is opened/resized, otherwise it may be necessary to add an attach listener to the legacy contents and a delay to the call, such as `dialog.getElement().executeJs("setTimeout(function(){ vaadin.forceLayout() }, 300)");`

**Comment by pleku** [comment]
Transferred to MPR as it was not dialog specific nor should there be anything done for this in dialog.
