### ISSUE TITLE
Introduce a compatibility chart in readme.md

### ISSUE THREAD

**Issue by mvysny** [vaadin/multiplatform-runtime#78]
Currently there are multiple releases of MPR: 2.0.5, but also 3.0.2 and 4.0.0 (see https://github.com/vaadin/multiplatform-runtime/tags ), yet it's not clear which version is compatible with which Vaadin 8/14/17 version. This information is present at https://vaadin.com/docs/v10/mpr/introduction/step-1-maven-v8.html but it's hopelessly outdated (uses MPR 1.1.1 at the time of writing).

Could you please make this information public in README.md? A chart akin to https://github.com/vaadin/vaadin-gradle-plugin/#compatibility-chart would help tremendously.

**Comment by pleku** [comment]
The MPR version is managed by `vaadin-bom` for the users. So when they use that, they get the correct version always.
https://github.com/vaadin/platform/blob/master/versions.json#L76

I don't see the added value of adding the readme just for one project as it would be outdated like documentation which to you refer to - we simply will not keep updating documentation for old platform versions.

**Comment by pleku** [comment]
This fact is even said in the very beginning of the linked documentation for v10
>Starting from Vaadin 12, MPR is part of the Vaadin Platform, so the supported version of the project is set for you when importing the plaform in your project. In other words, you only need to define the platform version:

**Comment by mvysny** [comment]
Thank you, that's excellent to know. In such case I think it would be beneficial for anybody interested to use MPR to have exactly the information stated in the README.md.

**Comment by mvysny** [comment]
https://github.com/vaadin/multiplatform-runtime/pull/79
