### ISSUE TITLE
Regression: MPR v2.0.6 does not work with IE11

### ISSUE THREAD

**Issue by TatuLund** [vaadin/multiplatform-runtime#81]
Technique used to fix the issue https://github.com/vaadin/multiplatform-runtime/issues/76 is using ResizeObserver in native JavaScript call in the client side code, that is not going thru frontend bundling and thus not getting polyfilled. According to CanIUse, (see https://caniuse.com/?search=resizeobserver) ResizeObserver is not supported by IE11.

**Comment by pleku** [comment]
There is at least a polyfill available which should work with IE11 https://www.npmjs.com/package/resize-observer-polyfill and it is even available via Bower if someone needs it for a webjar in compatibility mode. Including it to the project should be considered a workaround for now.

For addressing #76, maybe the code that sets up the resize observer should be moved to to a js-connector file that is subject to frontend build (and polyfilling). That way there would not be a need for including the polyfill separately. I don't know if it would be possible to use the polyfill as a ponyfill when needed (IE11) and that might be too complex.
