### ISSUE TITLE
Spike on implementing ViewScope for MPR-Spring

### ISSUE THREAD

**Issue by pleku** [vaadin/multiplatform-runtime#84]
Outcome is to see if it can be doable in a reasonable time. The other alternative we have is to just document the migration to use @RouteScope instead, but as that is a lot of more work, it would be great if MPR could have the added value of `@ViewScope` annotation that just works like in v7/v8.

It is enough to look at this for Spring projects for now.

**Comment by denis-anisimov** [comment]
`@RouteScope` without a `@RouteScopeOwner` may be used as a replacement for `ViewScope`  in case every view is Flow route target component.
Spring V8 add-on functionality is required to support V8 `ViewScope` (so it should be ported as additional Srping add-on for MPR).
