### ISSUE TITLE
MPR Project with Vaadin7 and Vaadin14 is not working in Internet Explorer and Edge

### ISSUE THREAD

**Issue by raja0812** [vaadin/multiplatform-runtime#87]
Hi,
We have configured our application with MPR
vaadin14 version :14.6.1
Flow version: 2.6.1
Vaadin7 version : 7.7.26
Vaadin mpr version: 2.2.0

Our main class is Extended from Flow Div. For all the Vaadin7 screens we get the Main Layout and then do a Legacy Wrap and add it to Flow Div. This works perfectly fine in Chrome. In Internet Explorer and Edge this is not working. The code is compiled in Production mode (clean package -Pproduction). 
2 files are uploaded the doc file shows some of the screen comparison between Chrome and Internet Explorer. The other one is the Chrome Debugger. 
Please look into this on priority.

Regards,
Raja Bhattacharjee

[MPR_ChromeVsIE.docx](https://github.com/vaadin/multiplatform-runtime/files/6663231/MPR_ChromeVsIE.docx)
![EdgeError](https://user-images.githubusercontent.com/86002595/122224996-4752e100-ced2-11eb-827a-e78dd13aca9d.PNG)

**Comment by caalador** [comment]
I couldn't replicate this with any of our demos.
Is it a theme issue?
What versions of Internet Explorer and Edge is used?
Is it possible to have a minimal project that would replicate the problem.

**Comment by raja0812** [comment]
Hi,
The replication source code have been uploaded by my colleague against (VS-3852 Urgent: Prioritization of Theming Issue with IE and Edge browsers).
And the version of browsers are
Internet Explorer:  11.576.14393.0
Edge: 38.14393.0.0

Regards,
Raja Bhattacharjee

**Comment by pleku** [comment]
Apparently this was not related to MPR code and handled through a EOD issue
