### ISSUE TITLE
URL parts of V10 are kept when navigating to V7 - when navigating "back", show router layout is not called

### ISSUE THREAD

**Issue by gilberto-torrezan** [vaadin/multiplatform-runtime#9]
@stefanuebe commented on [Tue Sep 04 2018](https://github.com/vaadin/multiplatform-runtime-internal/issues/211)

Following use case when using a router layout instance and a v7 navigator:

1. User navigates to v10 view "foo". Url becomes "/foo". showRouterLayout is called.
2. User navigatesto v7 view "bar". Url becomes "/foo#!bar". Content is updated by navigator view change listener.
3. User navigates to v10 view "foo". Url becomes "/foo", but showRouterLayout is not called and therefore the view content is not updated. 

Request is, that v10 should call showRouterLayout, too, when switching from v7 to v10

---

@caalador commented on [Fri Sep 07 2018](https://github.com/vaadin/multiplatform-runtime-internal/issues/211#issuecomment-419334851)

How is naviagtion executed? Is it just added to the url or through Navigator?
Is the view `foo` also a navigator content view?

**Comment by caalador** [comment]
Would also want to have a sample that shows how this works (e.g. doesn't work).

**Comment by caalador** [comment]
As a base rule stick the V7 navigator layout shouldn't a V10 layout that should work independently.
The showLayout is not called due to non mpr navigator and from flow point of view the route hasn't changed.
